General:
  app_name: load_cell_calculation
  version: 1.1
  link: https://github.com/shoetify/LoadCell_Analysis

Data_reading:

  WindSpeed_relationship: y=0.1726x-0.06956

  Sample_rate: 1000

  Stable_time_0Hz: 30

  Stable_time_others: 10

  Gap_before_next_wind_speed: 1

Data_calculation:

  air_density: 1.225

  cylinder_diameter: 0.06

  test_section_length: 1.32