General:
  app_name: load_cell_calculation
  version: 2.2
  link: https://github.com/shoetify/LoadCell_Analysis

Data_reading:

  WindSpeed_relationship: y=0.1726x-0.06956

  Sample_rate: 1000

  Stable_time_0Hz: 50

  Stable_time_others: 15

  Gap_before_next_wind_speed: 2

Data_calculation:

  ploy_deg: 1

  average_every: 1

  filtered_frequency: 0

  cylinder_diameter: 0.06

  test_section_length: 1.32